name: awfar_offers_dash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  country_code_picker: ^3.1.0
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.3
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.0
  go_router: ^14.3.0
  googleapis_auth: ^1.6.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  motion_toast: ^2.11.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: '>=8.0.0 <10.0.0'
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/