// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MqQrd_UO3uuYu2cnM7Ogulz0J8FNOCI',
    appId: '1:1067135384858:web:a478a25d518fec866e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    authDomain: 'com-awfaroffers-app-dev.firebaseapp.com',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    measurementId: 'G-WXLE6LDG5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxn2y9018fOh8wVWJZc4zXEBEiFSWE_50',
    appId: '1:1067135384858:android:0228fd6c7aa17f336e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZGIfSxQvwfhpNOPFg2Hs2blWwXujIgg',
    appId: '1:1067135384858:ios:bc79cb7e9a0cf8156e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.awfarOffersDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZGIfSxQvwfhpNOPFg2Hs2blWwXujIgg',
    appId: '1:1067135384858:ios:7c710b18e202c3686e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.awferOffersDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK9jfCvXsByO8vxBtoreZJL4owFMxFyJI',
    appId: '1:1067135384858:web:21896ee4db2ec3576e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    authDomain: 'com-awfaroffers-app-dev.firebaseapp.com',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    measurementId: 'G-9HP3RQEC9L',
  );

}